<img src="images/logo-2020.png" alt="frankfurt school hmi" style="width: 160px;"/>

# A brief introduction to pandas

[pandas](https://pandas.pydata.org/) is a Python package for working with labeled or relational data.  Specifically, pandas is ideally suited to work with

- matrix data with row and column labels
- ordered or unordered time-series data
- tabular data

pandas is designed to work intimately with [NumPy](https://numpy.org/devdocs/user/quickstart.html), so let's import both.

In [1]:
import pandas as pd
import numpy as np

# Series
A [Series](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html) is a single vector of data with an index that labels each element. The next line of code creates a pandas Series from the values `1493`, `1260`, `885`, and `650`. 

In [2]:
# example of a pandas Series
counts = pd.Series([1493, 1260, 885, 650]) 
counts

0    1493
1    1260
2     885
3     650
dtype: int64

In [3]:
# inspect the data type of 'counts'
type(counts)

pandas.core.series.Series

## Shape 
You can use the `.shape` method to inspect the shape of a Series

In [4]:
# inspect the shape of counts
counts.shape

(4,)

The Series `counts` consists of two colums.  The second column stores the four numbers, `1493`, `1260`, `885`, and `650`, as <i>values</i>.  The first column is a default sequence of integers assigned as an <i>index</i>.  Specifically, the collection of values of the `Series` is a NumPy array while the index is a pandas `Index` object. 

### Index and Values

We can return either the <b>values</b> or the <b>index</b> of a Series by the `.values` or `.index` methods, respectively.

In [5]:
counts.values

array([1493, 1260,  885,  650])

In [6]:
counts.index

RangeIndex(start=0, stop=4, step=1)

Note that the standard way that Python counts starts from 0 rather than from 1. (Why? The short answer is because zero is the smallest non-negative integer.) This is referred to as [zero-based indexing](https://en.wikipedia.org/wiki/Zero-based_numbering), and it is common in computer science.

Instead of the default index, we can instead assign meaningful labels to the data.  In our example, the four values are the populations (measured in units of 1000 people) of the following cities:

In [12]:
pop = pd.Series([1493, 1260, 885, 650], 
                       index=['San Antonio', 'Munich', 'San Francisco', 'Frankfurt'])
pop

San Antonio      1493
Munich           1260
San Francisco     885
Frankfurt         650
dtype: int64

Now, the labels can be used to refer to their corresponding values.

In [8]:
pop['Munich']

1260

Note that positional indexing can still be used:

In [9]:
# note that '1' indexes the second element
pop[1]

1260

We can give the array of values and indexes meaningful names, too.  In this case, the indexes are cities and the values populations

In [11]:
pop.name = 'Population'
pop.index.name = 'City'
pop

City
San Antonio      1493
Munich           1260
San Francisco     885
Frankfurt         650
Name: Population, dtype: int64

## NumPy math functions
NumPy mathematical operations can be applied to `Series` without destroying the data structure.

In [13]:
# total population of all four cities
np.sum(pop)

4288

In [14]:
# rescale population
np.multiply(pop,1000)

San Antonio      1493000
Munich           1260000
San Francisco     885000
Frankfurt         650000
dtype: int64

In [15]:
# arithmetical operations preserve data structure 
pop1 = np.multiply(pop,1000)
pop1

San Antonio      1493000
Munich           1260000
San Francisco     885000
Frankfurt         650000
dtype: int64

In [16]:
# original data structure
pop

San Antonio      1493
Munich           1260
San Francisco     885
Frankfurt         650
dtype: int64

## Filter by values in a Series

In [17]:
# Cities with less than 1 million people
pop[pop <1000]

San Francisco    885
Frankfurt        650
dtype: int64

In [18]:
# All cities that do not have a specific value (e.g., 885) 
pop[pop != 885]

San Antonio    1493
Munich         1260
Frankfurt       650
dtype: int64

# Dictionaries
A Series may also be thought of as an [ordered key-value](https://en.wikipedia.org/wiki/Key-value_database) database, a data structure that is sometimes referred to as a dictionary or a [hash table](https://en.wikipedia.org/wiki/Hash_table).  In pandas, the term  <b>dictionary</b> is used, and the convention `dict` is commonly used to name a pandas dictionary. 

In [20]:
# Create a city dictionary
city_dict = {'San Antonio': 1493, 'Munich': 1260, 'San Francisco': 885, 'Frankfurt': 650}

# Create the pandas Series named 'city' 
# from the dictionary named 'city_dict'
city = pd.Series(city_dict)
city

San Antonio      1493
Munich           1260
San Francisco     885
Frankfurt         650
dtype: int64

## Custom Indices
Suppose we create a Series from the dictionary `city_dict`, as before, but include a custom index that includes a new city name, `Lisbon`, but omits `Munich`:

In [21]:
city2 = pd.Series(city_dict, index=['San Antonio', 'Lisbon', 'San Francisco', 'Frankfurt'])
city2

San Antonio      1493.0
Lisbon              NaN
San Francisco     885.0
Frankfurt         650.0
dtype: float64

## NaN: 'Not a Number'
What the custom index in `city2` does is select the values keyed to `'San Antonio'`, `'San Francisco'`, and `'Frankfurt'` from `city_dict`, and treats any indices without a corresponding value in `city_dict` as missing.  In this example, the key `'Lisbon'` does not appear in `city_dict`, so its value is missing in the new Series `city2`.

pandas uses the type `NaN`, which stands for "<b>not a number</b>", for missing values.  We test whether a Series contains missing values with the method `.isnull()`.

In [22]:
# check for missing values
city2.isnull()

San Antonio      False
Lisbon            True
San Francisco    False
Frankfurt        False
dtype: bool

## Combining Series 
Adding two Series, such as `city` and `city2`, combines values with the same label.

In [23]:
city + city2 #city里面没有Lisbon的值，city2里面没有Munich的值，则相加之后这俩城市都没有值

Frankfurt        1300.0
Lisbon              NaN
Munich              NaN
San Antonio      2986.0
San Francisco    1770.0
dtype: float64

Notice that the population value for Munich in `city`, i.e., `1260`, is not carried through. Put differently, missing values are propagated by addition.  

Compare addition of Series to addition of two arrays of equal length in NumPy: NumPY combines values element-wise.  This can be checked with the method `.to_numpy()`)\.

In [24]:
# create np.arrays from Series
city_array = city.to_numpy()
city2_array = city2.to_numpy()

# combine arrays
city_array + city2_array

array([2986.,   nan, 1770., 1300.])

Here, we have (`1493` + `1493`), (`1260` + `NaN`), (`885` + `885`), and (`650` + `650`).  Notice that `NaN` is propagated through.  Why? Since `NaN` is not a number and arithematical operations only work on numbers, propagating `1260` instead would treat `NaN` as `0`, which is a number, thus rendering `NaN` ambiguous. 

As a practical matter, you typically want to know when and where values are missing in your data and that fact about your data set should not be hidden from you, or worse, altered, by an arithmetical operation. How you choose to deal with `NaN`s should be up to you: in some cases in will make sense to replace `NaN`s with zeros, but not in all cases. Perhaps it would be more reasonable to replace `NaN`'s in a column by the mean, median, or some other function of the data that isn't missing in that column. In other cases the best course of action might be simply to remove the rows with `NaN`'s from your dataset. 

---

# DataFrames
A Series associates a single value with an index. What about associating multiple values with an index?  This is necessary to work with data that is <b>multivariate</b>, where there are columns of data that may be of different types. [DataFrames](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html) are the pandas data objects designed for this purpose.

In [25]:
city_df = pd.DataFrame({'population':[1493, 1475, 1260, 885, 675, 650, 504, 249],
                       'city': ['San Antonio', 'Kyoto', 'Munich', 'San Francisco',
                                'Vancouver', 'Frankfurt', 'Lisbon', 'Porto'],
                       'country': ['USA', 'Japan', 'Germany', 'USA', 'Canada', 
                                   'Germany', 'Portugal', 'Portugal'],
                       'euro': [False, False, True, False, False, True, True, True]})
city_df

population           city   country   euro
0        1493    San Antonio       USA  False
1        1475          Kyoto     Japan  False
2        1260         Munich   Germany   True
3         885  San Francisco       USA  False
4         675      Vancouver    Canada  False
5         650      Frankfurt   Germany   True
6         504         Lisbon  Portugal   True
7         249          Porto  Portugal   True

In [26]:
# inspect the shape
city_df.shape

(8, 4)

Informally, the dataframe `city_df` has data about 8 cities in the form of four features, namely the city name, its population, the country that city is located in, and whether that country uses the Euro.  

Notice from this example that DataFrames have a default index, like we saw above with Series.  But instead of one column of values, there are many. (Here we have made the city name a column of values, rather than use them as an index.)  

In [27]:
# get information about the dataframe
city_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   population  8 non-null      int64 
 1   city        8 non-null      object
 2   country     8 non-null      object
 3   euro        8 non-null      bool  
dtypes: bool(1), int64(1), object(2)
memory usage: 328.0+ bytes


Notice too that the values are of <b>different types</b>: there are numbers (64 bit signed integers, `int64`, for populations), strings (`object`, the most general datatype, for city names and country names), and Boolean values (`bool`), for using the euro or not using the euro). 

---

# Basic data types (an aside)
We've seen `type()` used to determine the type of a Python object. Using `is` to create test conditions that return `True` or `False`, we can see syntax underlying some basic data types in Python.

In [28]:
# is a string?
type('') is str

True

In [29]:
# is a list?
type([]) is list

True

In [30]:
# is a dictionary?
type({}) is dict

True

In [31]:
# is an integer? 
type(0) is int

True

In [32]:
# is a floating point number?
type(0.0) is float

True

In [33]:
# is a boolean?
type(False) is bool

True

Returning to DataFrames. `df` is the common convention used to name variables which store DataFrames.  This, like other naming conventions, is for the convenience of humans writing code and for others who are reading your code.

## Column indexing
A DataFrame has an index for rows, as before, but also for columns. 

In [34]:
# row index (same as w/ Series) 
city_df.index

RangeIndex(start=0, stop=8, step=1)

In [35]:
# column index 
city_df.columns

Index(['population', 'city', 'country', 'euro'], dtype='object')

You can index a column by the dictionary key or by attribute.

In [36]:
# index a column by dict
city_df['country']

0         USA
1       Japan
2     Germany
3         USA
4      Canada
5     Germany
6    Portugal
7    Portugal
Name: country, dtype: object

In [37]:
# index a column by attribute (equivalent result)
city_df.country

0         USA
1       Japan
2     Germany
3         USA
4      Canada
5     Germany
6    Portugal
7    Portugal
Name: country, dtype: object

---
In either case, 

~~~python
city_df['country']
~~~

or

~~~python
city_df.country
~~~
indexing a column of a DataFrame returns the column as a Series.

In [38]:
# standard indexing of a column of 
# a DataFrame returns a Series
type(city_df['country'])

pandas.core.series.Series

## Row indexing
With Series, dictionary indexing retreived a particular element of the series -- a single element row. With DataFrames, use either `iloc` (integer-based indexing) or the `loc` attribute.

<b>Note:</b> You might find examples using the `ix` attribute, which was a hybrid of `iloc` and `loc`. However, `ix` has been depreciated.

In `city_df` example, the default integer index is the only index: we have not created an alternative. So, these integer indices are accessible by `iloc` and `loc`. 

In [45]:
# iloc uses the integer index
city_df.iloc[2]

population       1260
city           Munich
country       Germany
euro             True
Name: 2, dtype: object

In [43]:
# loc uses the integer index
city_df.loc[2]

population       1260
city           Munich
country       Germany
euro             True
Name: 2, dtype: object

## Filtering
The `.filtering()` method can be used to select a subset of rows or columns of a DataFrame according to index labels

In [50]:
city_df.filter(['city','population']) # = city_df[['city','population']]

city  population
0    San Antonio        1493
1          Kyoto        1475
2         Munich        1260
3  San Francisco         885
4      Vancouver         675
5      Frankfurt         650
6         Lisbon         504
7          Porto         249

## Boolean indexing
Alternatively, you can use the Boolean operators for <b>and</b>, <b>or</b>, and <b>not</b>:
 - and: `&`  
 - or: `|`  
 - not:  `~`  

to construct logical criteria applied to values in the DataFrame to select a subset. 

In [55]:
# Cities in North America
#  (City in USA OR City in Canada)
city_df[(city_df['country'] == 'USA') | (city_df['country'] == 'Canada')]

population           city country   euro
0        1493    San Antonio     USA  False
3         885  San Francisco     USA  False
4         675      Vancouver  Canada  False

In [56]:
# Cities not in North America
#  (NOT (City in USA OR City in Canada))
city_df[~((city_df['country'] == 'USA') | (city_df['country'] == 'Canada'))]

population       city   country   euro
1        1475      Kyoto     Japan  False
2        1260     Munich   Germany   True
5         650  Frankfurt   Germany   True
6         504     Lisbon  Portugal   True
7         249      Porto  Portugal   True

In [57]:
# Cities in North America smaller than 1 million people
#  (City population < 1M) AND (City in USA OR City in Canada)
city_df[(city_df['population']<1000) & 
        ((city_df['country'] == 'USA') | (city_df['country'] == 'Canada')) 
         ]

population           city country   euro
3         885  San Francisco     USA  False
4         675      Vancouver  Canada  False

## Sorting
A DataFrame may be sorted by the values of a column, a column may be selected and sorted its values, or a column selected and sorted by values in another column.

In [58]:
# sort city_df into alphabetical order of cities
city_df.sort_values('city')

population           city   country   euro
5         650      Frankfurt   Germany   True
1        1475          Kyoto     Japan  False
6         504         Lisbon  Portugal   True
2        1260         Munich   Germany   True
7         249          Porto  Portugal   True
0        1493    San Antonio       USA  False
3         885  San Francisco       USA  False
4         675      Vancouver    Canada  False

In [61]:
# Index cities and sort them
# Note that sort method only works on DataFrames
city_df[['city']].sort_values('city')

city
5      Frankfurt
1          Kyoto
6         Lisbon
2         Munich
7          Porto
0    San Antonio
3  San Francisco
4      Vancouver

In [64]:
# Sort cities by population (ascending order) then index the column city
# EXERCISE: Try indexing cities then sort by population, and then  
# explain the result: city_df[['city']] is a new df which has no data for population
city_df.sort_values('population')[['city']]

city
7          Porto
6         Lisbon
5      Frankfurt
4      Vancouver
3  San Francisco
2         Munich
1          Kyoto
0    San Antonio

## Reordering Columns
We can rearrange the columns in a DataFrame by rearranging the order of the column indices.

In [65]:
city_df[['city', 'population', 'country', 'euro']]

city  population   country   euro
0    San Antonio        1493       USA  False
1          Kyoto        1475     Japan  False
2         Munich        1260   Germany   True
3  San Francisco         885       USA  False
4      Vancouver         675    Canada  False
5      Frankfurt         650   Germany   True
6         Lisbon         504  Portugal   True
7          Porto         249  Portugal   True


## Creating a DataFrame Row-wise
Recall above that we used the following code to create `city_df` "column-wise":

~~~python

city_df = pd.DataFrame({'population':[1493, 1475, 1260, 885, 675, 650, 504, 249],
                       'city': ['San Antonio', 'Kyoto', 'Munich', 'San Francisco',
                                'Vancouver', 'Frankfurt', 'Lisbon', 'Porto'],
                       'country': ['USA', 'Japan', 'Germany', 'USA', 'Canada', 
                                   'Germany', 'Portugal', 'Portugal'],
                       'euro': [False, False, True, False, False, True, True, True]})

~~~

We could instead have created the same DataFrame row-wise:

In [66]:
city_df = pd.DataFrame([{'city': 'San Antonio', 'population': 1493, 'country': 'USA', 'euro': False},
                        {'city': 'Kyoto', 'population': 1475, 'country': 'Japan', 'euro': False},
                        {'city': 'Munich', 'population': 1260, 'country': 'Germany', 'euro': True},
                        {'city': 'San Francisco', 'population': 885, 'country': 'USA', 'euro': False},
                        {'city': 'Vancouver', 'population': 675, 'country': 'Canada', 'euro': False},
                        {'city': 'Frankfurt', 'population': 650, 'country': 'Germany', 'euro': True},
                        {'city': 'Lisbon', 'population': 504, 'country': 'Portugal', 'euro': True},
                        {'city': 'Porto', 'population': 249, 'country': 'Portugal', 'euro': True}])
city_df

city  population   country   euro
0    San Antonio        1493       USA  False
1          Kyoto        1475     Japan  False
2         Munich        1260   Germany   True
3  San Francisco         885       USA  False
4      Vancouver         675    Canada  False
5      Frankfurt         650   Germany   True
6         Lisbon         504  Portugal   True
7          Porto         249  Portugal   True

## adding a column

In [67]:
# Adding a column of identical values
city_df['year'] = 2019
city_df

city  population   country   euro  year
0    San Antonio        1493       USA  False  2019
1          Kyoto        1475     Japan  False  2019
2         Munich        1260   Germany   True  2019
3  San Francisco         885       USA  False  2019
4      Vancouver         675    Canada  False  2019
5      Frankfurt         650   Germany   True  2019
6         Lisbon         504  Portugal   True  2019
7          Porto         249  Portugal   True  2019

In [68]:
# Adding a column of distinct values
city_df['founded'] = [1718, 794, 1158, 1776, 1886, 794, -1200, -275]
city_df

city  population   country   euro  year  founded
0    San Antonio        1493       USA  False  2019     1718
1          Kyoto        1475     Japan  False  2019      794
2         Munich        1260   Germany   True  2019     1158
3  San Francisco         885       USA  False  2019     1776
4      Vancouver         675    Canada  False  2019     1886
5      Frankfurt         650   Germany   True  2019      794
6         Lisbon         504  Portugal   True  2019    -1200
7          Porto         249  Portugal   True  2019     -275

## adding a row
The `.append()` method is used to add rows to the end of a DataFrame. Any columns in the new row that do not appear in the target DataFrame will appear as new columns.

In [69]:
new_df = pd.DataFrame([{'city': 'London', 'population': 8797, 
                        'density (per sq km)': 4542,
                        'country': 'UK', 'euro': False, 'year':2019}])

In [70]:
# add new city
#  sort = False prohibts sorting columns 
#  by alphabetical order
city_df.append(new_df, sort=False) #出来london的index为0！！！！！

city  population   country   euro  year  founded  \
0    San Antonio        1493       USA  False  2019   1718.0   
1          Kyoto        1475     Japan  False  2019    794.0   
2         Munich        1260   Germany   True  2019   1158.0   
3  San Francisco         885       USA  False  2019   1776.0   
4      Vancouver         675    Canada  False  2019   1886.0   
5      Frankfurt         650   Germany   True  2019    794.0   
6         Lisbon         504  Portugal   True  2019  -1200.0   
7          Porto         249  Portugal   True  2019   -275.0   
0         London        8797        UK  False  2019      NaN   

   density (per sq km)  
0                  NaN  
1                  NaN  
2                  NaN  
3                  NaN  
4                  NaN  
5                  NaN  
6                  NaN  
7                  NaN  
0               4542.0

In [71]:
# fix row index
city_df.append(new_df, sort=False, ignore_index=True)

city  population   country   euro  year  founded  \
0    San Antonio        1493       USA  False  2019   1718.0   
1          Kyoto        1475     Japan  False  2019    794.0   
2         Munich        1260   Germany   True  2019   1158.0   
3  San Francisco         885       USA  False  2019   1776.0   
4      Vancouver         675    Canada  False  2019   1886.0   
5      Frankfurt         650   Germany   True  2019    794.0   
6         Lisbon         504  Portugal   True  2019  -1200.0   
7          Porto         249  Portugal   True  2019   -275.0   
8         London        8797        UK  False  2019      NaN   

   density (per sq km)  
0                  NaN  
1                  NaN  
2                  NaN  
3                  NaN  
4                  NaN  
5                  NaN  
6                  NaN  
7                  NaN  
8               4542.0

In [76]:
# update city_df to include London
city_df = city_df.append(new_df, sort=False, ignore_index=True)

## removing columns or rows
Columns can be removed by `del` or by the `.drop()` method.  Note that the `axis=1` argument is needed to specify column indices, and `axis = 0` is necessary to specify row indices. 

In [77]:
#drop 'year' column 
#  axis = 1 for column
#  axis = 0 for row
city_df = city_df.drop(['year'], axis = 1)
city_df

city  population   country   euro  founded  density (per sq km)
0    San Antonio        1493       USA  False   1718.0                  NaN
1          Kyoto        1475     Japan  False    794.0                  NaN
2         Munich        1260   Germany   True   1158.0                  NaN
3  San Francisco         885       USA  False   1776.0                  NaN
4      Vancouver         675    Canada  False   1886.0                  NaN
5      Frankfurt         650   Germany   True    794.0                  NaN
6         Lisbon         504  Portugal   True  -1200.0                  NaN
7          Porto         249  Portugal   True   -275.0                  NaN
8         London        8797        UK  False      NaN               4542.0

In [78]:
# drop row by index
city_df = city_df.drop([8], axis=0)
city_df

city  population   country   euro  founded  density (per sq km)
0    San Antonio        1493       USA  False   1718.0                  NaN
1          Kyoto        1475     Japan  False    794.0                  NaN
2         Munich        1260   Germany   True   1158.0                  NaN
3  San Francisco         885       USA  False   1776.0                  NaN
4      Vancouver         675    Canada  False   1886.0                  NaN
5      Frankfurt         650   Germany   True    794.0                  NaN
6         Lisbon         504  Portugal   True  -1200.0                  NaN
7          Porto         249  Portugal   True   -275.0                  NaN

##  Drop NaNs
A very useful method is [.dropna()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html), which allows you to remove missing values.  The default is to remove any (`how = 'any`) row (`index = 0`) in which a `NaN` value appears.

Compare two applications of `dropna()`

In [79]:
# default is axis = 0
city_df.dropna()

Empty DataFrame
Columns: [city, population, country, euro, founded, density (per sq km)]
Index: []

In [80]:
# axis = 1
city_df.dropna(axis=1)

city  population   country   euro  founded
0    San Antonio        1493       USA  False   1718.0
1          Kyoto        1475     Japan  False    794.0
2         Munich        1260   Germany   True   1158.0
3  San Francisco         885       USA  False   1776.0
4      Vancouver         675    Canada  False   1886.0
5      Frankfurt         650   Germany   True    794.0
6         Lisbon         504  Portugal   True  -1200.0
7          Porto         249  Portugal   True   -275.0